language: android
dist: trusty
sudo: required
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-28
before_script:
  - curl https://kaltura.github.io/fe-tools/android/license.sh | sh
script:
  - ./gradlew smartswitchplugin:build
after_failure:
  - cat smartswitchplugin/build/outputs/lint-results-debug.xml
notifications:
  email:
    recipients:
      - gilad.nadav@kaltura.com
      - gourav.saxena@kaltura.com
    on_success: always
    on_failure: always
